src/Entity/Membre.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MembreRepository")
 */


class Membre implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenomMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomDeSocieteMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $siretMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tvaMembre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateDeNaissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sexeMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresseMembre;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $cpMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $villeMembre;

    /**
     * @ORM\Column(type="string", length=13)
     */
    private $telephoneMembre;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\StatutMembre", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $idStatutMembre;

    /**
     * @ORM\Column(type="string", length=127, unique = true)
     */
    private $emailMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $passwordMembre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateEnregistrementMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $infoBancaireMembre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photoMembre;
    
    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;
    /**
    * @ORM\Column(type="array")
    */
    private $roles;
    
    // constructeur. Définit le statut actif et ajoute le role ADMIN automatiquement
    public function __construct()
    {
        $this->isActive = true;
        $this->roles[] = 'ROLE_USER';
    }

    public function getId()
    {
        return $this->id;
    }

    public function getNomMembre(): ?string
    {
        return $this->nomMembre;
    }

    public function setNomMembre(string $nomMembre): self
    {
        $this->nomMembre = $nomMembre;

        return $this;
    }

    public function getPrenomMembre(): ?string
    {
        return $this->prenomMembre;
    }

    public function setPrenomMembre(string $prenomMembre): self
    {
        $this->prenomMembre = $prenomMembre;

        return $this;
    }

    public function getNomDeSocieteMembre(): ?string
    {
        return $this->nomDeSocieteMembre;
    }

    public function setNomDeSocieteMembre(string $nomDeSocieteMembre): self
    {
        $this->nomDeSocieteMembre = $nomDeSocieteMembre;

        return $this;
    }

    public function getSiretMembre(): ?string
    {
        return $this->siretMembre;
    }

    public function setSiretMembre(string $siretMembre): self
    {
        $this->siretMembre = $siretMembre;

        return $this;
    }

    public function getTvaMembre(): ?string
    {
        return $this->tvaMembre;
    }

    public function setTvaMembre(string $tvaMembre): self
    {
        $this->tvaMembre = $tvaMembre;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->dateDeNaissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $dateDeNaissance): self
    {
        $this->dateDeNaissance = $dateDeNaissance;

        return $this;
    }

    public function getSexeMembre(): ?string
    {
        return $this->sexeMembre;
    }

    public function setSexeMembre(string $sexeMembre): self
    {
        $this->sexeMembre = $sexeMembre;

        return $this;
    }

    public function getAdresseMembre(): ?string
    {
        return $this->adresseMembre;
    }

    public function setAdresseMembre(string $adresseMembre): self
    {
        $this->adresseMembre = $adresseMembre;

        return $this;
    }

    public function getCpMembre(): ?string
    {
        return $this->cpMembre;
    }

    public function setCpMembre(string $cpMembre): self
    {
        $this->cpMembre = $cpMembre;

        return $this;
    }

    public function getVilleMembre(): ?string
    {
        return $this->villeMembre;
    }

    public function setVilleMembre(string $villeMembre): self
    {
        $this->villeMembre = $villeMembre;

        return $this;
    }

    public function getTelephoneMembre(): ?string
    {
        return $this->telephoneMembre;
    }

    public function setTelephoneMembre(string $telephoneMembre): self
    {
        $this->telephoneMembre = $telephoneMembre;

        return $this;
    }

    public function getIdStatutMembre()
    {
        return $this->idStatutMembre;
    }

    public function setIdStatutMembre($id): self
    {
        $this->idStatutMembre = $id;

        return $this;
    }

    public function getEmailMembre(): ?string
    {
        return $this->emailMembre;
    }

    public function setEmailMembre(string $emailMembre): self
    {
        $this->emailMembre = $emailMembre;

        return $this;
    }
    
    //GESTION PASSWORD//////////////////////////
    
    //méthode imposée par l'interface
    public function getUsername(): ?string
    {
        return $this->emailMembre;
    }
    // méthode imposée par l'interface
    public function setUsername(string $emailMembre): self
    {
        $this->emailMembre = $emailMembre;
        return $this;
    }
    //méthode imposée par l'interface
    public function getPassword(): ?string
    {
        return $this->passwordMembre;
    }
    public function getPasswordMembre(): ?string
    {
        return $this->passwordMembre;
    }
    //méthode imposée par l'interface
    public function setPassword(string $passwordMembre): self
    {
        $this->passwordMembre = $passwordMembre;
        return $this;
    }
    
    public function setPasswordMembre(string $passwordMembre): self
    {
        $this->passwordMembre = $passwordMembre;

        return $this;
    }
    ////////////////////////////


    public function getDateEnregistrementMembre(): ?\DateTimeInterface
    {
        return $this->dateEnregistrementMembre;
    }

    public function setDateEnregistrementMembre(\DateTimeInterface $dateEnregistrementMembre): self
    {
        $this->dateEnregistrementMembre = $dateEnregistrementMembre;

        return $this;
    }

    public function getInfoBancaireMembre(): ?string
    {
        return $this->infoBancaireMembre;
    }

    public function setInfoBancaireMembre(string $infoBancaireMembre): self
    {
        $this->infoBancaireMembre = $infoBancaireMembre;

        return $this;
    }

    public function getPhotoMembre()
    {
        return $this->photoMembre;
    }

    public function setPhotoMembre($photoMembre): self
    {
        $this->photoMembre = $photoMembre;

        return $this;
    }
    
    ///Les fonction à rajouter pour Membre //////////////////////
    //récupération des rôles
    public function getRoles()
    {
        return $this->roles; //return ['ROLE_USER'];
    }
    //récupération du "salt" (null car bscript le fait automatiquement)
    public function getSalt()
    {
        return null;
    }
    //fonction imposée par l'interface user
    public function eraseCredentials()
    {
    }
    //sérialisation de l'utilisateur (pour stocker en session)
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->emailMembre,
            $this->passwordMembre,
            $this->isActive
        ));
    }
    //dé-sérialisation de l'objet (session)
    public function unserialize($serialized)
    {
        list($this->id, 
                 $this->emailMembre,
                 $this->passwordMembre,
                 $this->isActive)
        = unserialize($serialized);
    }
    //ajout d'un role
    public function setRoles($val)
    {
        return $this->roles[] = $val;
    }
    //compte non expiré?
    public function isAccountNonExpired()
    {
        return true;
    }
    //Compte non vérouillé
    public function isAccountNonLocked()
    {
        return true;
    }
    //  identifiants non expirés
    public function isCredentialsNonExpired()
    {
        return true;
    }
    // est activé
    public function isEnabled()
    {
        return $this->isActive;
    }
}

src/Controller/SecurityController.php
<?php
namespace App\Controller;
//src/Controller/SecurityController

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
//sécurité
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
//pour utiliser les annotations
use Symfony\Component\Routing\Annotation\Route;

// table utilisateurs pour enregistrer un nouvel utilisateur
use App\Entity\Membre;

// table Produit pour enregistrer une nouvelle reservation
use App\Entity\Produit;

// table Salle pour récupérer l'id de la salle
use App\Entity\Salle;

// pour le formulaire de reservation, aller charger la table Indisponible pour rentrer les lignes de reservation
use App\Entity\Indisponible;

//pour le calendrier
use App\Services\Calendrier;

//formulaire inscription
use App\Form\MembreType;

//formulaire reservation
use App\Form\ReservationType;

//formulaire pour proposer une salle
use App\Form\OffreSalleType;

//gerrer upload photo profil
use App\Services\UploadPhotoMembre;

class SecurityController extends Controller
{
	/* Inscription d'un utilisateur
	affiche le formulaire et ajoute l'utilisateur dans la table user 
	*/
    
	/**
	* @Route(
	*	  "/inscription",
	*	  name="inscription")
	*/
	public function inscription(Request $request, UserPasswordEncoderInterface $passwordEncoder, UploadPhotoMembre $fileUploader)
	{
		//liaison avec la table des utilisateurs
		$membre = new Membre();
		//création du formulaire
		$form = $this->createForm(MembreType::class, $membre);

		//récupération des données du formulaire
		$form->handleRequest($request);
        
		//si soumis et validé
		if($form->isSubmitted() && $form->isValid())
		{
            //on recupere les information du formulaire
            /*$membre = $form->getData();*/ //??????????????????????????hnadleRequest?????
            
            // Upload photo //////////////////////////////////////
            
            $photoProfil = $membre->getPhotoMembre();
            $fileName = $fileUploader->upload($photoProfil);
            
            $membre->setPhotoMembre($fileName);

            ////Fin de uploadphoto/////////////////////////////////////////////////////
            
            //le siret n'est pas obligatoirement rempli dans mon formulaire d'inscription. 
            //Donc j'applique une contrainte ici si il est rempli            
            /*if(strlen($form->getSiretMembre()) > 0 && strlen($form->getSiretMembre()) =! 14)
            {
                return "Le Numéro Siret doir comporter 14 chiffres";
                //attention !!! ce code n'est pas sur...
            }*/
            
            //enregistrer la date du jour au format SQL pour enregistrer dans la table
            $dateEnregistrement = new \DateTime(); 
            $membre->setDateEnregistrementMembre($dateEnregistrement);
            
            //enregistrer en automatique des infos, c'est fictif, pour ne pas faire planter la requete sql
            $infosCarteBancaire = 'CB'; 
            $membre->setInfoBancaireMembre($infosCarteBancaire);
            
            
			//encodage du mot de passe
			$hash = $passwordEncoder->encodePassword($membre, $membre->getPasswordMembre());
			$membre->setPasswordMembre($hash);
            
            
			//enregistrement dans la table
			$em = $this->getDoctrine()->getManager();
			$em->persist($membre);
			$em->flush();
            
            
            

			//retour à l'accueil
			return $this->redirectToRoute('connexion');
		}
		//affichage du formulaire
		return $this->render('security/inscription.html.twig',
									array('form' => $form->createView(),
												'title' => 'inscription'));
	}
    
    /*POUR LA PHOTO DE PROFIL*/
    
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

	/**
	* @Route(
	*		"/connexion",
	*	  name="connexion")
	*/
	public function connexion(Request $request, AuthenticationUtils $authUtils)
	{
		//récupération de l'erreur si besoin
		$error = $authUtils->getLastAuthenticationError();
		//dernier username saisi
		$lastUsername = $authUtils->getLastUsername();

		//affichage du formulaire
		return $this->render('security/connexion.html.twig',
							array('last_username' => $lastUsername,
										'error' => $error,
										'title' => 'connexion'));
	}
    
    /**
	* @Route(
	*	  "/offreSalle",
	*	  name="offreSalle")
	*/
	public function offreSalle(Request $request)
	{
		//liaison avec la table des utilisateurs
		$nouvelleSalle = new Salle();
		//création du formulaire
		$form = $this->createForm(OffreSalleType::class, $nouvelleSalle);
        
		//récupération des données du formulaire
		$form->handleRequest($request);
        
		//si soumis et validé
		if($form->isSubmitted() && $form->isValid())
		{
            //recuperer l'id membre via la session pour le mettre en BDD
            //Pour recuperer l'id lui donner le lien de la table suffit, on ne lui donne pas le champ à aller chercher. Le manyToOne se fait tout seul.
            $idMembre = $this->getUser();
            $nouvelleSalle->setIdMembre($idMembre);
            
            //recuperer le nom de la salle pour generer une reference unique en incluant son nom
            $nomSalle = $nouvelleSalle->getNomSalle();
            
            //creation d'une reference en automatique
            $referenceUnique = $nomSalle . rand(1,10000);
            $nouvelleSalle->setReferenceSalle($referenceUnique);
            
			//enregistrement dans la table
			$em = $this->getDoctrine()->getManager();
			$em->persist($nouvelleSalle);
			$em->flush();
            
			//retour au tableau de bord pour voir notre reservation
			return $this->redirectToRoute('tableauDeBord');
		}
		//affichage du formulaire
		return $this->render('security/offreSalle.html.twig',
									array('form' => $form->createView(),
												'title' => 'offreSalle'));
	}
}

templates/security/admin.html.twig
{# admin.html.twig#}
{# on appelle ce fichier via notre SecurityController.php#}


{% extends 'base.html.twig' %}


{% block title %} {{title}} {% endblock %}

{% block body %}
   


<div class="row">
  
   <div class="col-sm-3">
       
   </div>
   
   <div class= "col-sm-6">
            
        <h1>Ma page Admin</h1>
        
        <h2> Bonjour {{ app.user.username }} !</h2>
        
        <p>Lorem Ipsum {{ app.user.email }} </p>
        
        <p>Lorem Ipsum {{ app.user.password }} </p>
        
        <p>Lorem Ipsum {{ app.user.id }} </p>
        
        <p>Lorem Ipsum {{ app.user.isActive }} </p>
        
        {% for roles in app.user.roles %}
           <ul>
                <li> {{ roles }} </li>
            </ul>
        {% endfor %}

       
   </div>
    
</div>
        
       

{% endblock %}

templates/security/connexion.html.twig
{# templates/public/template.html.twig #}

{% extends 'base.html.twig' %}

{#HEAD#}
    {% block title %} {{ title }} {% endblock %}
    {% block meta_description %}Connexion à EasyOffice{% endblock %}
    {% block stylesheets %}
        <link href="{{ asset('css/connexion.css') }}" rel="stylesheet">
    {% endblock %}

{#FIN DE HEAD#}

{#HEADER#}
    {% block header %} {% endblock %}
{% block searchbar %} {% endblock %}
{#FIN DE HEADER#}

{#MAIN#}
{% block main %}
    <div class="container">
        <div class="row align-items-center">
            <div class="col-sm-4">

                {# affichage des messages d'erreurs#}
                {% if error %}
                    <div class="alert alert-danger text-center">
                        {{ error.messageKey|trans(error.messageData, 'security') }}
                    </div>
                {% endif %}
            </div>

            <div class="col-sm-5">
                <!-- form card login -->
                <div class="card rounded-0 shadow-lg p-3 mb-5">
                    <div class="card-header">
                        <h3 class="mb-0">Connexion</h3>
                    </div>
                    <div class="card-body">
                        <form class="form" role="form" autocomplete="off" id="formLogin" novalidate="" method="POST">
                            <div class="form-group">
                                <label for="uname1">Email :</label>
                                <input type="text" name ="_username" values="{{ last_username }}" class="form-control form-control-lg rounded-0 border-right-0 border-top-0 border-left-0 border border-success font-weight-bold" name="uname1" id="uname1" required="" placeholder="Email">
                                <div class="invalid-feedback">Oops, email invalide</div>
                            </div>
                            <div class="form-group second-box">
                                <label>Mot de passe :</label>
                                <input type="password" name ="_password" class="border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control form-control-lg rounded-0" id="pwd1" required="" autocomplete="new-password" placeholder="Mot de passe">
                                <div class="invalid-feedback">Entrer votre mot de passe!</div>
                            </div>
                            <button type="submit" class="btn btn-success btn-lg float-right" id="btnLogin">Login</button>
                        </form>
                    </div>
                    <!--/card-block-->
                </div>
                <!-- /form card login -->
            </div>

        </div>
    </div>

{% endblock %}
{#FIN DE MAIN#}

{# SCRIPT #}
    {% block javascripts %}{% endblock %}
{# FIN DE SCRIPT #}

templates/security/inscription.html.twig
{# templates/public/template.html.twig #}

{% extends 'base.html.twig' %}

{#HEAD#}
    {% block title %}  {{ title }} {% endblock %}
    {% block meta_description %}Inscription à EasyOffice{% endblock %}
    {% block stylesheets %}
        <link href="{{ asset('css/inscription.css') }}" rel="stylesheet">
    {% endblock %}

{#FIN DE HEAD#}

{#HEADER#}
    {% block header %} {% endblock %}
{#FIN DE HEADER#}

{#MAIN#}
{% block main %}

    <!--
    <div class="col-sm-6">
        {#
        affichage des messages flash
        {% for message in app.flashes('message') %}
        <div class="alert alert-success text-center">
        {{ message }}
        </div>
        {% endfor %}
        #}
    </div>
    -->

    <!--Formulaire d'inscription-->
    <div class="container big-box shadow-lg p-3 mb-5">
        <div class="container box-titre">
            <div class="row">
                <div class="titre font-weight-bold">Inscription</div>
            </div>
        </div>

        <div class="box-register row align-items-center">
            <div class="col-md-6 left-column col align-self-start">
                <!-- form card login -->
                {{ form_start(form) }}

                {#formulaire bootstrap#}

                <div class="form-group hidden">
                    {{ form_row(form.nomMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Nom" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.prenomMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Prénom" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.nomDeSocieteMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Nom de la société " } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.siretMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Siret de la société" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.tvaMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Numéro de TVA" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.dateDeNaissance, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Date de naissance" } }) }}
                </div>


                    <div class="form-inline font-weight-bold">
                        {{ form_row(form.sexeMembre, {attr: {class: "font-weight-bold form-check-input rounded-0" } }) }}
                    </div>


                <div class="form-group hidden">
                    {{ form_row(form.adresseMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Adresse" } }) }}
                </div>



            </div><!-- fin du col-md-6 -->

            <div class="col-md-6 right-column">

                <div class="form-group hidden">
                    {{ form_row(form.cpMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Code postal" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.villeMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Ville" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.telephoneMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Téléphone (ex: 0608090810)" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.idStatutMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Nom" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.emailMembre, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Email" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.passwordMembre.first, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Mot de passe" } }) }}
                </div>

                <div class="form-group hidden">
                    {{ form_row(form.passwordMembre.second, {attr: {class: "border-right-0 border-top-0 border-left-0 border border-success font-weight-bold form-control rounded-0 border border-secondary", placeholder: "Confirmer le mot de passe" } }) }}
                </div>

                <div class="form-group border-right-0 border-top-0 border-left-0 border border-success font-weight-bold">

                    {{ form_row(form.photoMembre, {attr: {class: "font-weight-bold form-control rounded-0"} }) }}
                </div>

            </div><!-- fin du col-md-6 -->

            <div class="form-group text-center">
                <button type="submit" class="btn btn-success">Enregistrer</button>
            </div>
            {{ form_end(form) }}

        </div><!-- fin du row -->
    </div><!-- fin du container -->

{% endblock %}
    {#FIN DE MAIN#}

    {#SCRIPT#}
    {% block javascripts %}{% endblock %}
{#FIN DE SCRIPT#}

templates/security/login.html.twig
{# formTest.html.twig#}
{# on appelle ce fichier via notre TestController.php#}


{% extends 'base.html.twig' %}
{# il retoutre le fichier même si on est pas dans le même dossier, il remonte au dossier parent. Par contre si il etait dans un autre sous dossier, il faudrait le repreciser#}

{% block title %} {{title}} {% endblock %}

{% block body %}
   


<div class="row">
  
   <div class="col-sm-3">
       
          {# affichage des messages d'erreurs#}
            {% if error %}
                <div class="alert alert-danger text-center">
                    {{ error.messageKey|trans(error.messageData, 'security') }}
                </div>
            {% endif %}
   </div>
   
   <div class= "col-sm-6">
      
       <fieldset>
           <legend>Connexion</legend>
            
               <form action="{{ path('login') }}" method="post">
                   <div class="form-group">
                      <label for="username">
                          Username : 
                      </label>
                      <input type="text" name ="_username" values="{{ last_username }}" class="form-control">
                   </div>
                   
                   <div class="form-group">
                      <label for="password">
                          Password : 
                      </label>
                      <input type="password" name ="_password" class="form-control">
                   </div>
                   
                   {##}
                   
                   <div class="form-group text-center">
                       <button type="submit" class="btn btn-success">Login</button>
                   </div>
               </form>

           
        </fieldset>
       
   </div>
    
</div>
        
       

{% endblock %}

templates/security/offreSalle.html.twig
{# templates/public/template.html.twig #}

{% extends 'base.html.twig' %}

{#HEAD#}
    {% block title %} {{ title }} {% endblock %}
    {% block meta_description %}Le truc qui apparait dans les recherches google{% endblock %}
    {% block stylesheets %}{% endblock %}

{#FIN DE HEAD#}


{#HEADER#}
    {% block header %} <h1>Proposer une salle</h1> {% endblock %}
{#FIN DE HEADER#}


{#MAIN#}
{% block main %}
        <!--Formulaire d'inscription-->
        <div class="row">
           <div class="col-sm-3" ></div>
            <div class="col-sm-6">
                {#
                    affichage des messages flash
                    
                    {% for message in app.flashes('message') %}
                        <div class="alert alert-success text-center">
                            {{ message }}
                        </div>
                    {% endfor %}
                #}
            </div>
        </div>
        
        <div class="row">
        
            <div class= "col-sm-6">
                <fieldset>
                   <legend>Proposer une salle</legend>

                        {{ form_start(form) }}

                        {#formulaire bootstrap#}

                        {# generer la reference de la salle dans le publicController #}
                        <div class="form-group">
                            {{ form_row(form.nomSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.adresseSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.cpSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.villeSalle, {attr: {class: "form-control"} }) }}
                        </div>
                        
                        {#ATTENTION ICI CEST UNE CLE ETRANGERE POUR RECUPERER LES NOMS DE CATEGORIES#}                        
                        <div class="form-group">  
                            {{ form_row(form.idCategorieSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.surfaceSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.descriptionSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.nbrPieceSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.capaciteSalle, {attr: {class: "form-control"} }) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form.prixSalle, {attr: {class: "form-control"} }) }}
                        </div>
                        
                        {#ATTENTION ICI CEST UNE CLE ETRANGERE POUR RECUPERER LES NOMS D'EQUIPEMENTS#}
                        <div class="form-group">
                            <div class="form-check form-check-inline">  
                                {{ form_row(form.equipementSalle, {attr: {class: "form-check-input"} }) }}
                            </div>
                        </div>
                        
                        {# LE BOUTON SUBMIT EST DANS OffreSallType #}

                        
                        <div class="form-group">
                             {{ form_end(form) }}
                       </div>

                </fieldset>
            </div><!--FIN DE CLASS-->
        </div><!--FIN DE ROW-->

    {% endblock %}
{#FIN DE MAIN#}

{#SCRIPT#}
    {% block javascripts %}{% endblock %}
{#FIN DE SCRIPT#}